// 表示文字列の日本語平易化辞書（BuildBase S3a）。
//
// ここは表示直前の文字列変換のみを担う。型定義・APIキー・DB/CSVカラム名・
// ロジック上のステータス比較（例: status === 'proposed'）は一切変更しない。
// 新しい表示語彙を追加する場合はここに追記し、JSX側は t() 経由で参照すること。
export const TERM_JA: Record<string, string> = {
  golden: '確定値',
  source_chain: '根拠',
  observed: '有報の項目',
  concept: '表の項目',
  mapping: '対応付け',
  corroboration: '数値照合',
  needs_reconciliation: '検算不一致',
  needs_review: '要確認',
  single_source: '単一ソース',
  auto_confirmed: '自動確定',
  review_queue: 'レビュー候補',
  source_audit: '抽出根拠',
  cell_resolutions: 'セル別の照合判定',
  accept: '候補値を採用',
  correct: '手入力で修正',
  reject: '候補を却下',
  not_applicable: '対象外',
  idle: '待機中',
  running: '実行中',
  failed: '失敗',
  succeeded: '成功',
  pending: '未完了',
  incomplete: '照合未完了',
  completed: '照合完了',
  pass: '照合済み',
  mismatch: '数値不一致',
  no_mapping: '対応項目なし',
  factbook_only: 'Factbook専用',
  outside_result_period: '結果表の対象年度外',
  factbook: '公式Factbook',
  missing_yuho_value: '結果表が空欄',
  missing_yuho_row: '結果表の行なし',
  missing_factbook_value: 'ファクトブック値が数値化不可',
  not_parsed: '未抽出',
  forecast_not_checked: '予測値のため未照合',
  data_scope_mismatch: '範囲が違う',
  validation_fail: '検算エラー',
  validation_warn: '検算注意',
  validation_pass: '検算OK',
  ok: 'OK',
  corroboration_conflict: '根拠間で不一致',
  different_scope: '範囲が違う',
  confidence_below_threshold: '信頼度が低い',
  multiple_xbrl_candidates: '有報タグ候補が複数',
  unit_unknown: '単位未判定',
  xbrl_tag_not_found: '有報タグ未検出',
  existing_human_reviewed: '過去の人手確認あり',
  existing_value_mismatch: '過去確認値と不一致',
  cell_workbench_manual: 'セル作業から手入力',
  blank: '空欄',
  consolidated: '連結',
  standalone: '単独',
  segment: 'セグメント',
  permit_entity: '許認可主体',
  current_year: '当期',
  period_end: '期末時点',
  duration: '期間累計',
  use: '用途別',
  business_scope: '建築/土木等',
  building_orders_by_use: '用途別受注',
  completed_building_by_use: '用途別完工',
  building_orders_by_business_scope: '建築/土木等別受注',
  completed_building_by_business_scope: '建築/土木等別完工',
  factbook_or_ir_data: 'ファクトブック/IR資料',
  XBRL_CSV: 'XBRL自動抽出',
  LOCAL_TABLE: '表から抽出',
  MANUAL_OBSIDIAN: '手入力データ',
  normal: '通常',
  has_proposals: '対応候補あり',
  none: 'なし',
  unsupported: '未対応',
  success: '成功',
  complete: '完了',
  company_year_id: '会社・年度ID',
  field_id: '項目ID',
  confidence: '信頼度',
  buckets: '照合元の種類',
  sources: '照合元',
  decided_at_utc: '判定日時',
  candidate_id: '候補ID',
  proposed: '提案中',
  confirmed: '確定済み',
  rejected: '却下済み',
  active: '有効',
  merged: '統合済み',
  retired: '廃止',
  restatement: '訂正の疑い',
  deterministic: '自動一致',
  unverifiable: '照合不能',
  office: '事務所',
  factory: '工場・生産施設',
  housing: '住宅',
  commercial: '商業施設・店舗',
  medical_welfare: '医療・福祉',
  education_research: '教育・研究',
  lodging: '宿泊施設',
  logistics: '倉庫・流通施設',
  public_cultural: '公共・文化施設',
  other_use: 'その他用途',
  development_other: '開発事業等',
};

/** 用語辞書に基づく表示文字列変換。未登録キーはそのまま返す。 */
export function t(key: string): string {
  return TERM_JA[key] ?? key;
}
